Donation view first version without backend
Giveth/giveth-io-typescript pull request #20
Opened 2021-11-30 22:16 UTC by mateodaza

2021-12-02 22:41 UTC, RamRamez requested changes
Thanks @mateodaza. It's great just some minor fixes.

2021-12-02 22:41 UTC, RamRamez commented on src/apollo/apolloClient.ts
> +  const httpLink = createUploadLink({
I think we don't need to use createUploadLink. Use `createHttpLink` instead

2021-12-02 22:41 UTC, RamRamez commented on src/apollo/apolloClient.ts
> +    uri: process.env.NEXT_PUBLIC_APOLLO_SERVER,
You can use `config.ts` here. No need to pass env.
We save all needed variables in the config file.

2021-12-02 22:41 UTC, RamRamez commented on src/apollo/auth.js
> +export const isBrowser = () => typeof window !== 'undefined'
You can remove this file (`auth.js`). I'm saving user data on the UserProvider component.

2021-12-02 22:41 UTC, RamRamez commented on src/apollo/gql/gqlProjects.ts
> +      users {
Is it necessary to use `users`? why not using `adminUser`?
As I remember, `users` was null for some reason for some of the projects.

2021-12-02 22:41 UTC, RamRamez commented on src/components/project-card/ProjectCard.tsx
> +  const name = users?.length > 0 && users[0].name
why not using `adminUser` here?
This way project owner is not shown on project cards anymore.

2021-12-02 22:41 UTC, RamRamez commented on src/components/project-card/ProjectCard.tsx
> +const NoImg = styled.div`
you can remove them.

2021-12-02 22:41 UTC, RamRamez commented on src/components/project-card/ProjectCardAlt.tsx
> +            <Caption>Raised: $200</Caption>
You can use `totalDonations` for this.

2021-12-02 22:41 UTC, RamRamez commented on src/components/project-card/ProjectCardAlt.tsx
> +            <Caption>Last updated: 5 days ago</Caption>
You can use `updatedAt` for this.

2021-12-02 22:41 UTC, RamRamez commented on src/components/project-card/ProjectCardAlt.tsx
> +const Wrapper2 = styled.div`
`Wrapper2` was used for hover state for project cards. You can remove it here.

2021-12-02 22:41 UTC, RamRamez commented on src/components/views/donate/CryptoDonation.tsx
> +  flex: row;
`flex-direction` ?

2021-12-02 22:41 UTC, RamRamez commented on src/components/views/donate/DonateIndex.tsx
> +const ProjectsIndex = (props: IProjectBySlug) => {
It should be `DonateIndex`

2021-12-02 22:41 UTC, RamRamez commented on src/components/views/donate/DonateIndex.tsx
> +      <Wrapper>
It has `border-radius` on design

2021-12-02 22:41 UTC, RamRamez commented on pages/project/[slug].tsx
> +      admin: project.adminUser,
Is it used anywhere?

2021-12-02 22:41 UTC, RamRamez commented on src/components/project-card/ProjectCard.tsx
> +  isNoImg,
not used.

2021-12-02 22:41 UTC, RamRamez commented on src/components/project-card/ProjectCardAlt.tsx
> +  const projectImage = () => {
you can use `ProjectCardImage` instead.

2021-12-02 22:41 UTC, RamRamez commented on src/components/project-card/ProjectCardAlt.tsx
> +        <ImagePlaceholder>{projectImage()}</ImagePlaceholder>
`<ImagePlaceholder>
          <ProjectCardImage image={image} cardWidth={cardWidth} cardRadius={cardRadius} />
        </ImagePlaceholder>`

2021-12-02 22:41 UTC, RamRamez commented on src/components/views/donate/DonateIndex.tsx
> +          </Right>
please also add share buttons on the design

2022-01-10 13:15 UTC, mateodaza commented on src/apollo/apolloClient.ts
> +  const httpLink = createUploadLink({
We need uploadLink to be able to send images through graphql, it's gonna be needed when we implement create/edit projects

2022-01-10 15:45 UTC, merged